apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: u20041-kworker3-dev:5000/myappws
      context: ../jhipster-k8s
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
