apiVersion: v1
kind: Secret
metadata:
  name: myappws-postgresql
  namespace: jd-n1
  labels:
    app: myappws-postgresql
type: Opaque
data:
  postgresql-password: ZmUwNDcwYTgwNTk1ODljMjY5NzhkZTViMmI0YzM3ZWVmYWQ5YWRmZTc4NmRmY2Q3NzBmNjZkY2ZkMjg4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappws-postgresql
  namespace: jd-n1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappws-postgresql
  template:
    metadata:
      labels:
        app: myappws-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.3
          env:
            - name: POSTGRES_USER
              value: myAppWs
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myappws-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: myappws-postgresql
  namespace: jd-n1
spec:
  selector:
    app: myappws-postgresql
  ports:
    - port: 5432
